#pragma once

enum stackException
{
	STACK_OVERFLOW = 1,
	STACH_UNDERFLOW,
	STACK_SAFE_RESIZE,
	STACK_ERROR_SIZE,
	STACK_ERROR_INDEX,
	MULTISTACK_OVERFLOW,
	MULTISTACK_UNKNOW_EXCEPTION,
	MULTISTACK_SAFE_RESIZE
};